import { OnInit, ElementRef, EventEmitter, Renderer2 } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { CommandExecutorService } from './common/services/command-executor.service';
import { MessageService } from './common/services/message.service';
export declare class NgxEditorComponent implements OnInit, ControlValueAccessor {
    private _messageService;
    private _commandExecutor;
    private _renderer;
    editable: boolean;
    spellcheck: boolean;
    placeholder: string;
    translate: string;
    height: string;
    minHeight: string;
    width: string;
    minWidth: string;
    toolbar: Object;
    resizer: string;
    config: {
        editable: boolean;
        spellcheck: boolean;
        height: string;
        minHeight: string;
        width: string;
        minWidth: string;
        translate: string;
        enableToolbar: boolean;
        showToolbar: boolean;
        placeholder: string;
        imageEndPoint: string;
        toolbar: string[][];
    };
    showToolbar: boolean;
    enableToolbar: boolean;
    imageEndPoint: string;
    blur: EventEmitter<string>;
    focus: EventEmitter<string>;
    textArea: any;
    ngxWrapper: ElementRef;
    Utils: any;
    private onChange;
    private onTouched;
    constructor(_messageService: MessageService, _commandExecutor: CommandExecutorService, _renderer: Renderer2);
    onTextAreaFocus(): void;
    onEditorFocus(): void;
    onContentChange(innerHTML: string): void;
    onTextAreaBlur(): void;
    resizeTextArea(offsetY: number): void;
    executeCommand(commandName: string): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    refreshView(value: string): void;
    togglePlaceholder(value: any): void;
    getCollectiveParams(): any;
    ngOnInit(): void;
}
